services:
  catalog:
    build: ./services/catalog-service
    ports:
      - "3001:3001"
  inventory:
    build: ./services/inventory-service
    ports:
      - "3002:3002"
  orders:
    build: ./services/orders-service
    ports:
      - "3003:3003"
  payment:
    build: ./services/payment-service
    ports:
      - "3004:3004"
  shipping:
    build: ./services/shipping-service
    ports:
      - "3005:3005"
  feedback:
    build: ./services/feedback-service
    ports:
      - "3006:3006"
